### ISSUE TITLE
OpenGL.Net 0.2.1 NuGet packcage seems to be missing GlControl

### ISSUE THREAD

**Issue by beyon** [luca-piccioni/OpenGL.Net#10]
Release notes lists the addition of the GlControl, however it doesn't seem to be actually included in the package.

I can use the GlControl only after cloning the repo and building the solution myself.

**Comment by LebedevaElen** [comment]
The same problem. No GLControl in Toolbox and it can't be added.

**Comment by luca-piccioni** [comment]
I'll check within the next week.

Il mer 13 lug 2016, 11:03 LebedevaElen <notifications@github.com> ha
scritto:

**Comment by csh** [comment]
Any update on this?

**Comment by luca-piccioni** [comment]
Yesterday I've released an updated version of the library. Due some unexpected trouble I've compiled it using Mono 4.2 on Linux. It should work all the same.

If someone can confirm that on Windows platform is working, I'll close the issue.

**Comment by luca-piccioni** [comment]
The GlControl doesn't show in the Toolbox bar, but now the control is up and running.
