### ISSUE TITLE
Unable to use two GlControls in the same form

### ISSUE THREAD

**Issue by tumblingstuff** [luca-piccioni/OpenGL.Net#102]
Did you ever come up with a solution to this? My application requires two contexts in a single form, and I keep getting failures when both contexts are updated - whether trying to update one while the other is animated (always), or even just occasionally. I've tried blocking so that only one context is sending Gl commands at a time with a mutex - no luck.

**Comment by luca-piccioni** [comment]
You are required to update controls using a timer. GLcontrol implementation already provide this in Animation properties.

**Comment by tumblingstuff** [comment]
Running one with the animation timer while loading a 3D texture into the second results in an "invalid operation" failure of the second. And even without the timer updating the first, I _still_ get occasional failures. I'm at the point of looking for other C#/OpenGL interfaces, which stinks because yours is the 3rd I've tried... 3D textures (volume rendering) aren't supported by most of them (for example, OpenTK).

I'm going to try overriding the OnPaint calls, setting a flag for timer updates, and see if I can improve matters. 

Does .Refresh work better than .Invalidate (which I've been using so far) for the GlControls?

**Comment by tumblingstuff** [comment]
Sorry if I sound grumpy - I'm learning OpenGL at the same time, and while I've (finally) worked through the functionality I need these last bugs are preventing project completion.

**Comment by tumblingstuff** [comment]
Sigh - overrode OnPaint for the UserControl wrapping the GlControls, just setting a flag for update picked up by a timer and calling .Refresh on the control. The two GlControls are still trashing each other, whether animated or not.

It's nice framework, but this bug is a project killer for me. Now looking for alternative bindings...

**Comment by luca-piccioni** [comment]
You must be sure to have the correct GL context current, otherwise state and obnects are mixed up.

Despiteit seems related to the project, the problem you're facing is cause how GL is designed, and how GL relates with the underlying windowing system.

Even if you try to change bindings, you will end up to the same conclusion.

**Comment by luca-piccioni** [comment]
Little tip.

If you need two widgets for splitting vertically a view, you should use a single control and use glViewport to manage updated areas.

**Comment by tumblingstuff** [comment]
Where/how can I make the context current? I've looked for but not found a .MakeCurrent function...

**Comment by tumblingstuff** [comment]
The project I'm working on requires a 3D volumetric view and a 'terrain' plot of a single slice, in two windows.

**Comment by tumblingstuff** [comment]
Or rather, two panes or usercontrols on the main form.

**Comment by tumblingstuff** [comment]
...And MakeCurrentContext, while visible in the Object browser, isn't exposed when coding. Hmm. I've tried obtaining the .BindingContext on context creation, and setting the bindingcontext in my locking mutex, no success. 

_How_ do I make the context for a GlControl current?

**Comment by luca-piccioni** [comment]
Isn't this [template](https://github.com/luca-piccioni/OpenGL.Net/tree/master/Samples/ContextSharing/SingleContext) working for you?

**Comment by tumblingstuff** [comment]
Let me dig into that - I had the impression the sample was for sharing a single context in multiple views, rather than two separate scenes/viewers.

**Comment by luca-piccioni** [comment]
> How do I make the context for a GlControl current?

Cache the RenderContext field of the argument of the GlControl.ContextCreated event.

Then you can call `GlControl.Device.MakeCurrent(cachedRenderContext)`; Or just inherith from GlControl, and call `MakeCurrentContext()`.

At the moment _RenderContext protected field is not exposed as public API. Or just checkout the project and modify for your needs. The code is not complicated as it seems.

**Comment by tumblingstuff** [comment]
That looks like it's eliminated the errors - thanks, and thanks for putting up with an OpenGL novice. Now, just a bit more cleanup on my LUT transfer functions, and I should be good to go...
