### ISSUE TITLE
modern opengl doesn't work

### ISSUE THREAD

**Issue by zengxiuhao** [luca-piccioni/OpenGL.Net#111]
Now,I use  This Opengl.Net library  to draw Triangle.
When I use VAO VBO Object, the triangle don't display in the glcontrol and the window remain the backgroundcolor.   the same code can run correctly in opentk.
However,When I use fixed pipeline to draw triange,it display correctly.

**Comment by zengxiuhao** [comment]
I don't know how to resolve it .
Can you give me a simple demo that use VAO、Vbo to draw triange in glcontrol.

**Comment by zengxiuhao** [comment]
I don't know how to resolve it .
Can you give me a simple demo that use VAO、Vbo to draw triange in glcontrol.

**Comment by luca-piccioni** [comment]
Did you read the HelloTriangle sample source? It does render using VAO. (https://github.com/luca-piccioni/OpenGL.Net/blob/master/Samples/HelloTriangle/SampleForm.cs)
