### ISSUE TITLE
GL methods overload problem in VB.net

### ISSUE THREAD

**Issue by vsantalov** [luca-piccioni/OpenGL.Net#12]
Method overloading differences between C# and VB.Net cause errors in VB.Net. To VB byRef and byVal do not differentiate the function and an ambiguous member error occurs.

**Comment by luca-piccioni** [comment]
Sorry, but CLS compliance is not a requirement for me. If you're able to contribute by building a CLS compliant OpenGl.Net version, you're welcome.

**Comment by luca-piccioni** [comment]
Sure the issue affect few dozen of methods because case sensitivity; for example, _glClear_ is confused with _GL_CLEAR_. Can you be more specific for your case(s)? I don't remember that overloads are differentiated by argument attributes.
