### ISSUE TITLE
ShaderPreprocessorParser.cs may be incomplete

### ISSUE THREAD

**Issue by enoughpoints** [luca-piccioni/OpenGL.Net#130]
Parser method is missing in ShaderPreprocessorParser.cs at line 322

**Comment by luca-piccioni** [comment]
It is generated dynamically by Pegasus based on the relative grammar file.

Maybe Nuget packages are not installed correctly.

**Comment by enoughpoints** [comment]
Thanks for the reply ,now the problem is solved. Great works!

**Comment by luca-piccioni** [comment]
Thanks.

Keep attention: I just found a bug in the preprocessor logic about #elif statement... I'll correct it within the next days.
