### ISSUE TITLE
Gl.ShaderBinary causes infinite recursion

### ISSUE THREAD

**Issue by GiantBlargg** [luca-piccioni/OpenGL.Net#136]
https://github.com/luca-piccioni/OpenGL.Net/blob/75f50d6a21bf3d506c7b6fb7702dbdfd2b54791d/OpenGL.Net/Gl.VERSION_4_1.cs#L519 calls itself, perhaps it should call the other function of the same name: https://github.com/luca-piccioni/OpenGL.Net/blob/75f50d6a21bf3d506c7b6fb7702dbdfd2b54791d/OpenGL.Net/Gl.VERSION_4_1.cs#L549

**Comment by luca-piccioni** [comment]
Thank you for finding this, Probably there are others. I won't apply your pull request, because the source code is automatically generated, and the culprit must be found in the source code generator.

**Comment by GiantBlargg** [comment]
Thanks for the quick response.

I like the added convenience that my solution has of not having to specify the count, would it be possible to add a function with the signature `ShaderBinary(uint[] shaders, int binaryformat, object binary, int length)`
