### ISSUE TITLE
Drop WinForms dependency

### ISSUE THREAD

**Issue by prasannavl** [luca-piccioni/OpenGL.Net#14]
Following this PR https://github.com/luca-piccioni/OpenGL.Net/pull/13, WinForms as a dependency can be completely dropped, and GLControl moved into a separate project, making the wrappers independent of the platform. 

Unfortunately, I don't have the time right now to submit a PR for that as well. But, just creating an issue to track it, if that is indeed a forward direction for the project :)

**Comment by luca-piccioni** [comment]
You've read my mind, actually. I'm too busy too, at least for the next month.

Currently I'd like to create two separated projects, one fo WinForms, and the other for GTK# (since recently I've switched to Linux on my personal computer, and Monodevelop don't offer a WinForms designer). 

Consider it done. But at the moment I'm really busy to have fun on it.

**Comment by mattleibow** [comment]
I want to spend some time on something like this. I want to get this to work with any platform, such as iOS and Android. And UWP via ANGLE. I am currently working on a project that uses a bit of OpenGL, so I have a few small members. I can't promise anything yet, but moving WinForms into a separate assembly will allow for more platforms to be added.

**Comment by prasannavl** [comment]
@mattleibow, awesome. I had the same thing on my to-do list for a while. Same 3 platforms + Win32 (but without WinForms or WPF using the raw Win32 API - turns out, you can ease the GC a lot and park yourself in the C/C++ perf zone by not using WinForms which allocates quite a few objects almost every message in the event loop - Makes zero difference in regular apps though, but comes in handy for games, high perf apps , or ones that use `PeekMessage` like APIs to throw out tons of messages a second). 

Anyway, been making a lot of abstractions for cross platform raw message/event loops off late, all in C#, but still very much a work in progress. Been caught up so far. Great to hear your team may be on it!

**Comment by prasannavl** [comment]
@luca-piccioni - Perfect! Cheers. :)
