### ISSUE TITLE
unable to set pixel format

### ISSUE THREAD

**Issue by TheBoJaN** [luca-piccioni/OpenGL.Net#15]
I'm having trouble getting the GlControl to work. Just adding it to a form and this is all I get:
![image](https://cloud.githubusercontent.com/assets/3692535/18771887/cfd599bc-80ff-11e6-950a-3e4ae85795d5.png)

I've tried both the nu-get package and the latest master, both have the same result.

I should also note, I'm running a GTX 1080 FE with up to date drivers.

**Comment by TheBoJaN** [comment]
Changing Depth Bits from the default 0 to 8 seems to have fixed it. I'm fairly new to opengl, what should I have it set at?

**Comment by luca-piccioni** [comment]
Pixel format selection is always a pain. I'll try to add additional debug information for thus specific case. 

In the meanwhile, can you list the available pixel formats oc your driver? Just for the record, setting 0 bits for depth buffer is usually allowed.

**Comment by TheBoJaN** [comment]
Here you go.
[formats.txt](https://github.com/luca-piccioni/OpenGL.Net/files/491305/formats.txt)

I have a project that I believe was working on my old GTX 680 just fine but gave me the same error as above on my new card and again, changing depth bits fixed it. Maybe it's got something to do with the pascal architecture in the new cards.

**Comment by luca-piccioni** [comment]
My conjecture is that the DeviceContextCollection.Choose routine has choosen a non-displayable pixel format. Setting the depth causes the algorithm to select a pixel format that is displayable.

The last commit display a more informative exception message, telling you the index of the pixel format is trying to set.
