### ISSUE TITLE
Visual Studio 2015 to 2019 glControl designer view crashes in windows 10

### ISSUE THREAD

**Issue by Mariano-EC** [luca-piccioni/OpenGL.Net#151]
Hi, i'm working in a solution using vs2019 (also tried 2015-2017 with same error) c# winforms using the OpenGL.NET.glControl.
When i try to open the form in design view, vs crashes and restarts. After debugging the designer (with a second vs instance, attached to devenv.exe process) it throws an unhandled exception, copied below*.

If i don't open the design view the program runs smoothly, so it is not a runtime error. 
Furthermore i found that this only happens when vs is using my Nivida GPU (checked with system monitor). If i disable the Nvidia card, and only use the integrated gpu (intel 630) this problem doesn't arise. 

Another very strange behaviour: if I get into form Desing View, but by chance the glControl is not visible (for instance, it is completely covered by a docked Error List Window), the problem doesn't arise, until the very moment glcontrol gets visible again (even partially visible). This shows the problem appears when any part of glControl tries to be rendered in Design view.   

Configuration:
CPU: intel 8700
OS: windows 10 1903
GPU: tested both in Nvidia 1070 TI and Nvidia 710 TI independently.
GPU Drivers: Latest 441
RAM: 16GB DDR4
IDE: Visual Studio 2019
Project: Winfows Forms  c# .Net Framework 4.52 / 4.61
Library: OpenGL.Net and OpenGL.Net.Winforms Packages 0.84/ and below

Steps To Reproduce:

Way 1:
- Open visual studio using Nvidia GPU (in Task Manager GPU is 1)
- Create new Windows Forms c# .Net Framework  Project
- Add OpenGL.Net and OpenGL.Net.Winforms Packages
- (optional) Add GLControl to toolbox.
-Add GLControl to Form1 
-Visual studio CRASHES! and sometimes with the following message
![image](https://user-images.githubusercontent.com/60009441/72628306-caae8280-392c-11ea-9935-676c56a8b6ab.png)

 --------------------------------------------------------
WAY 2

- open VS using integrated GPU ( typically displayed as GPU 0 on Task Manager)
- Create new Windows Forms c# .Net Framework  Project
- Add OpenGL.Net and OpenGL.Net.Winforms Packages
- (optional) Add GLControl to toolbox.
- Add GLControl to Form1 
- Close Form1, Save and Close Project, and close Visual Studio
- Open visual studio using Nvidia GPU
- Double click Form1 to view Designer
- Visual studio CRASHES! and restart with no message

* Unhandled Exception: 

System.TypeInitializationException
  HResult=0x80131534
  Message=The type initializer for 'OpenGL.Egl' threw an exception.
  Source=OpenGL.Net.WinForms
  StackTrace:
   at OpenGL.GlControl.DrawDesign(PaintEventArgs e)
   at OpenGL.GlControl.OnPaint(PaintEventArgs e)
   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   at System.Windows.Forms.Control.WmPaint(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ContainerControl.WndProc(Message& m)
   at System.Windows.Forms.UserControl.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Design.ControlDesigner.DesignerWindowTarget.DefWndProc(Message& m)
   at System.Windows.Forms.Design.ControlDesigner.WndProc(Message& m)
   at System.Windows.Forms.Design.ControlDesigner.DesignerWindowTarget.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Inner Exception 1:
AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

Thanks in advance for your help, and congrats for a great Library!!

Yours, 

Mariano

**Comment by luca-piccioni** [comment]
It seems that EGL bindings on some NVIDIA driver is not correct, corrupting the stack. Since the GL control query GL information even when running in the designer, bad thing happens.

Try to set OPENGL_NET_EGL_STATIC_INIT to NO on Visual Studio process. 

(https://github.com/luca-piccioni/OpenGL.Net/wiki/GL-%5C-Initialization)

**Comment by Mariano-EC** [comment]
Thank you very much for your quick response. Appreciated a lot.

I tried setting the enviroment variable using System.Environment.SetEnvironmentVariable("OPENGL_NET_EGL_STATIC_INIT", "NO");

I tried it inside the Initialize() method of Form1.Designer.cs, but it is still crashing when switching to Design View (besides, all code I put in Form1.Designer.cs will dissapear at soon as the Form is modified in design view, right?). I was hoping the code used to show Design view was that, but probably not. I'm not sure which code is the one running to make the Design view at real-time.

This is the code I tried at Form1.Designer.cs and didn't work: 
-----------------------------------------
namespace testopengl
{
    partial class Form1
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;       
        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.Environment.SetEnvironmentVariable("OPENGL_NET_EGL_STATIC_INIT", "NO"); //this is the added line, just before glcontrol creation. 
            this.glControl1 = new OpenGL.GlControl();
            this.SuspendLayout();
            // 
            // glControl1
            // 
            this.glControl1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.glControl1.ColorBits = ((uint)(24u));
            this.glControl1.DepthBits = ((uint)(0u));
            this.glControl1.Location = new System.Drawing.Point(273, 126);
            this.glControl1.MultisampleBits = ((uint)(0u));
            this.glControl1.Name = "glControl1";
            this.glControl1.Size = new System.Drawing.Size(441, 246);
            this.glControl1.StencilBits = ((uint)(0u));
            this.glControl1.TabIndex = 1;
            // 
            // Form1
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(800, 450);
            this.Controls.Add(this.glControl1);
            this.Name = "Form1";
            this.Text = "Form1";
            this.ResumeLayout(false);

        }

        #endregion      
        private OpenGL.GlControl glControl1;
    }
}
-----------------------------------------

I'm quite new at this and maybe I didn't set the enviroment variable correctly or at the right place. Maybe the best is to roll back to old Nvidia drivers? 

Thank you very much for your help!

Mariano

**Comment by luca-piccioni** [comment]
I mean, set the environment in the user profile (system wide), and only then start visual studio (which inherith system environment).

**Comment by Mariano-EC** [comment]
Worked like a charm! Thank you! Thought maybe it was something I could change locally for that project only, sorry for being such a noob =)

Congrats again for building such an useful tool!!
