### ISSUE TITLE
glGenVertexArrays() shows NullReferenceException

### ISSUE THREAD

**Issue by linatpensyl** [luca-piccioni/OpenGL.Net#154]
Hi,

When I run Gl.glGenVertexArrays() on my laptop and my laptop is connected with an extended monitor, this function doesn't report any error. However, if I unplug the monitor and run it again it pops up NullReferenceException 'Object Reference not set to an instance of an object'. I can repro this on your project https://github.com/luca-piccioni/OpenGL.Net/blob/5dad7512bebadfb128ffd388d1f84b42123443c7/Samples/HelloTriangle.WPF/MainWindow.xaml.cs . Just add `Gl.GenVertexArray();` under `Gl.Clear(ClearBufferMask.ColorBufferBit);` and run the program with and without second monitor .  Would you like to help me with this?
![Capture](https://user-images.githubusercontent.com/58703096/75177314-e7945d80-5703-11ea-922b-c832bc8e0342.JPG)

**Comment by luca-piccioni** [comment]
The fuction pointers in the Thread Local Storage. They are initialized whenever a context is make current (maybe only on Windows, I'm not sure).

Maybe WPF is restarting in another thread?

Maybe you can hook the event and make current the GL context on the drawing thread (that should have changed), but it is fairly inefficient.

Maybe you can remove the TLS attribute on delegates. But this need code changes, and I'm not aware of any technique to remove that attribute (apart patching the binary).

**Comment by linatpensyl** [comment]
I am running opengl .net (c#). Something happen when I used nuget to download the latest version opengl .net.

**Comment by linatpensyl** [comment]
Or, maybe I misunderstood your question, Would you like to clarify that?

**Comment by linatpensyl** [comment]
Okay. This is because I have two graphic cards on my laptop, NVIDIA and INTEL. I disabled my INTEL graphic card so that the computer is forced to use NVIDIA one. This somehow cause error `Gl.GenVertexArray(); `, and I need to connect put to another monitor to enable opengl. If I enable my INTEL graphic card again everything is fine.
