### ISSUE TITLE
Xamarin support

### ISSUE THREAD

**Issue by matyasf** [luca-piccioni/OpenGL.Net#16]
Does this project work with desktop Xamarin, Xamarin.Android and Xamarin.iOS?

**Comment by luca-piccioni** [comment]
I'm playing right now with Xamarin.Android, and the support seems promising. I got running the library on Android emulator, and now I'm trying to harmonize the current code base for running also on Android using Xamarin.

When I'll get a triangle on Android I'll let you know here.

Instead, about Xamarin.iOS, I don't know if I'm able to support it since I've no iOS virtual/real device for developing the library.

**Comment by matyasf** [comment]
Great! I do have an iOS device, so I can make a PR  after I got it working on Android and figure out how to make it work on iOS.

**Comment by matyasf** [comment]
Hello

I am trying to get your code working on Android, but the GL context creation fails.
This is my code (copied from OpenGL.Net.Xamarin.Android/GLSurfaceView.cs):

            // Get actual native window handle
            _NativeWindowHandle = ANativeWindow_fromSurface(JNIEnv.Handle, holder.Surface.Handle);

            // Create device context
            _DeviceContext = DeviceContext.Create(_NativeWindowHandle);
            _DeviceContext.IncRef();

            // Set pixel format
            DevicePixelFormatCollection pixelFormats = _DeviceContext.PixelsFormats;
            DevicePixelFormat controlReqFormat = new DevicePixelFormat();

            controlReqFormat.RgbaUnsigned = true;
            controlReqFormat.RenderWindow = true;
            controlReqFormat.ColorBits = 24;
            //controlReqFormat.DepthBits = (int)DepthBits;
            //controlReqFormat.StencilBits = (int)StencilBits;
            //controlReqFormat.MultisampleBits = (int)MultisampleBits;
            //controlReqFormat.DoubleBuffer = true;

            List<DevicePixelFormat> matchingPixelFormats = pixelFormats.Choose(controlReqFormat);
            if (matchingPixelFormats.Count == 0)
                throw new InvalidOperationException("unable to find a suitable pixel format");

it always throws the "unable to find a suitable pixel format" exception.

the app logs the following:
OpenGLRenderer( 6268): Use EGL_SWAP_BEHAVIOR_PRESERVED: true
I/OpenGLRenderer( 6268): Initialized EGL, version 1.4

I've debugged inside NativeDeviceContext.cs, and found that `_DeviceContext.PixelsFormats` returns a 0 lenght list because the for loop in `get PixelsFormats` always continues at this point:

    if (Egl.GetConfigAttrib(_Display, config, Egl.NATIVE_RENDERABLE, out param) == false)
						throw new InvalidOperationException("unable to get configuration parameter NATIVE_RENDERABLE");
    if (param == Egl.TRUE)
        continue; // my app always continues here

even though `configCount` is 56. This is a Xperia Z5 running Android 6 if this helps.

**Comment by luca-piccioni** [comment]
I think that the conditional should be inverted: we want EGL_NATIVE_RENDERABLE to True. Isn't it?  The question is: how could I run on emulator flawlessly? 

I may try ony phones. I few weeks I should have my Z5 too.

**Comment by matyasf** [comment]
Meanwhile I've tested it on a Nokia N1 tablet (running a,most stock Android 5.1.1) and it runs there perfectly. btw heres my code: https://github.com/fmotagarcia/sparrow-sharp/blob/starling_201/SparrowSharp.Android/Core/AndroidViewController.cs

**Comment by matyasf** [comment]
Also another thing thats wonky on Adnroid: When I try to include the source of OpenGL.NET in an Android project the compilation fails in GetProcAddress line 301:     
`Environment.SetEnvironmentVariable("PATH", String.Format("{0};{1}", path, libraryDirPath), EnvironmentVariableTarget.Process);` with the error that this function can only accept 2 arguments. I guess the mono version of mscorlib does not need the third parameter thus they removed it? I've worked around by including an ifdef, but I guess the proper solution would be to put this into the Windows specific project?

**Comment by matyasf** [comment]
I've played around with the Android version a bit, and it works nicely. There are still some issues (e.g. GLSurfaceView swallows all my errors), but overall I got it working nicely on Android and Windows in a crossplatform Xamarin project. I will open new, more specific PRs/issues if I run into something.
