### ISSUE TITLE
'Object reference not set to an instance of an object.'

### ISSUE THREAD

**Issue by Flow75** [luca-piccioni/OpenGL.Net#164]
Hello, 

Since today, 

When I use Gl.Ortho, I've the following exception, I don't know why 

![image](https://user-images.githubusercontent.com/47718818/185430496-c291ccea-eb45-4e66-bef9-d8f5c1ca1c2a.png)

can you help me ?
Thx.

**Comment by luca-piccioni** [comment]
Does [this](https://github.com/luca-piccioni/OpenGL.Net/wiki/GL-%5C-Common-mistakes)   solve your issue?

**Comment by Flow75** [comment]
Thank you
