### ISSUE TITLE
Equivalent of Glu.LookAt

### ISSUE THREAD

**Issue by Flow75** [luca-piccioni/OpenGL.Net#165]
Hello, 

I'm looking to the method "LookAt", 

I've looking the Wiki and no reference about its equivalence in the Opengl.NET world.

Thx.
F.

**Comment by luca-piccioni** [comment]
[This](https://github.com/luca-piccioni/OpenGL.Net/blob/master/OpenGL.Net/Matrix.cs#L5754)  should be equivalent to the GLU utility.
