### ISSUE TITLE
Build instructions don't actually work.

### ISSUE THREAD

**Issue by johnfredcee** [luca-piccioni/OpenGL.Net#18]
Zaba@ZABA-HUGETOP D:\Dev\libraries\OpenGL.Net
> msbuild OpenGL.Net.sln
Microsoft (R) Build Engine version 14.0.25420.1
Copyright (C) Microsoft Corporation. All rights reserved.

Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
Build started 16/10/2016 10:59:27.
D:\Dev\libraries\OpenGL.Net\OpenGL.Net.sln : Solution file error MSB5004: The solution file has two projects named "OpenGL_Net".

Build FAILED.

  D:\Dev\libraries\OpenGL.Net\OpenGL.Net.sln : Solution file error MSB5004: The solution file has two projects named "OpenGL_Net" .

    0 Warning(s)
    1 Error(s)

**Comment by luca-piccioni** [comment]
Funny.  I'll check it tonight. Instead, executing ms build on All_Vc14.sln?

Il Dom 16 Ott 2016 12:00 John Connors <notifications@github.com> ha scritto:

**Comment by johnfredcee** [comment]
Yes, that's what I'm doing..

**Comment by luca-piccioni** [comment]
Found the reason. OpenGL.Net.sln is a MonoDevelop solution that includes the OpenGL.Net.mdproj project (binary package project). MSBuild is confusing them (probably ignore the extension (sigh) and hence the error.

Documentation should be completed differentiating for build tool-chain.
