### ISSUE TITLE
What is OpenGL.HAL?

### ISSUE THREAD

**Issue by matyasf** [luca-piccioni/OpenGL.Net#20]
I am trying to understand how your library works and was wondering what this project is. For me it looks like some library/framework used to render graphics and geospatial data. Is this somehow closely tied to the OpenGL.NET project? Because I am just looking for C# OpenGL bindings not a graphics framework.

Thanks!

**Comment by luca-piccioni** [comment]
It is an abstraction built on top of OpenGL.Net. Just use OpenGL.Net, and
ignore the OpenGL.Hal.

Il Mar 18 Ott 2016 01:36 matyasf <notifications@github.com> ha scritto:
