### ISSUE TITLE
Examples of rendering to a hidden window...

### ISSUE THREAD

**Issue by equinox2k** [luca-piccioni/OpenGL.Net#25]
Hi been trying to work out how to render to a hidden form as wanting to write a console application that renders content saves the back buffer without a form appearing.

Any examples or pointers to how to manually create the context etc would be appreciated...

**Comment by luca-piccioni** [comment]
Currently I've not introduced any off-screen support, but I'm working on it just right now. What platform are you targeting?

**Comment by equinox2k** [comment]
Targeting windows console app also ASP.Net controller.

Id also like to say thank you for creating such a great library, I had originally done application using OpenTK and was very easy to port over.

**Comment by equinox2k** [comment]
Hi, just given it a whirl and seems to work perfectly thanks :)

**Comment by equinox2k** [comment]
Spoke a bit to soon, console application works perfectly, in a web context the DeviceContext.Create() returns null (Caching made me think it was working), will investigate further...

**Comment by luca-piccioni** [comment]
If ASP.Net is executed by a service, there are no chance to get any GPU context, since the service is running on OS session 0, which forbid iteraction with the graphics system. 

You're best bet is to integrate the GL application running on another session or on another computer, and get ghe information via IPC.

**Comment by equinox2k** [comment]
Yeah, I thought I had got around that issue in past by doing equivalent of...

var form = new Form();
using (DeviceContext deviceContext = DeviceContext.Create(IntPtr.Zero, form.Handle))

which was enough to give the service a form handle to generate things from

**Comment by luca-piccioni** [comment]
If DX are working in that environment, you can try to use GLES2 over ANGLE: in this way you can use DX wrapped on GLES API.

Set at first Egl.IsRequired as true, and see Egl static constructor how to  provide ANGLE libs.
