### ISSUE TITLE
ANGLE DLL's

### ISSUE THREAD

**Issue by equinox2k** [luca-piccioni/OpenGL.Net#29]
Hi,

I understand in order to get ANGLE working you need the two dll's libEGL + libGLESv2 however Ive tried adding the dll's from the nugget packages mentioned here https://github.com/Microsoft/angle, however the sample app says they are not correct for application. Do the dll's come from somewhere else?

**Comment by luca-piccioni** [comment]
I currently use the Google branch of ANGLE. However, I think this is not the source of the problem. 

What is the actual exception you get? Probably the error is caused by missing dependencies or architecture mismatch.

**Comment by equinox2k** [comment]
I'm not at computer at moment but is basically saying the EGL environment is not available. I.e no difference in error if I copy dlls to project bin folder or not. I've just started to try and compile googles ANGLE so will see if that makes any difference

**Comment by luca-piccioni** [comment]
Read the wiki:
https://github.com/luca-piccioni/OpenGL.Net/wiki/OpenGL-ES-using-ANGLE

Il gio 15 dic 2016, 09:44 Peter Tribe <notifications@github.com> ha scritto:

**Comment by equinox2k** [comment]
I read the wiki but got confused as search paths mentioned WinRT where I thought that was Arm based rather than 32/64 also wasn't sure if the Angle path was relevant to exe ...

Sent from my iPhone

On 15 Dec 2016, at 00:46, Luca Piccioni <notifications@github.com<mailto:notifications@github.com>> wrote:

Read the wiki:
https://github.com/luca-piccioni/OpenGL.Net/wiki/OpenGL-ES-using-ANGLE

Il gio 15 dic 2016, 09:44 Peter Tribe <notifications@github.com<mailto:notifications@github.com>> ha scritto:

**Comment by luca-piccioni** [comment]
The search path are relative to the current working directory. The directory structure is currently derived by the ANGLE output. 

I've never tested on ARM architecture since I have no Win10 on ARM. However,  ANGLE is available for ARM also.

**Comment by equinox2k** [comment]
Still having problems getting ANGLE working.

I have created an archive of the HelloTraiangle.ANGLE sample [https://www.dropbox.com/s/zgwymy9w1c4x11q/HelloTriangle.ANGLE.zip?dl=0](https://www.dropbox.com/s/zgwymy9w1c4x11q/HelloTriangle.ANGLE.zip?dl=0)

inside it in the bin\Debug folder you will see hello_triangle.exe which is a exe compiled from googles ANGLE + dependant dll's and runs fine.

However running the HelloTriangle.ANGLE.exe produces error "EGL/ANGLE platform not available"

Hope you can help...

**Comment by luca-piccioni** [comment]
![angle](https://cloud.githubusercontent.com/assets/4700681/21242338/2699803c-c314-11e6-8d85-a9abe28a83c8.png)

You miss to build the directory tree for supporting ANGLE on x86/x64 - debug/release. See the picture: you need to provide `ANGLE\winrt10\x64\libEGL.dll` and `ANGLE\winrt10\x64\libGLESv2.dll` to support an EGL+GLES2  implementation. Files are relative to the current working directory, usually the executable path.
If you run on x86, you must provide `ANGLE\winrt10\x86\` directory structure. Follow patterns found in [wiki ](https://github.com/luca-piccioni/OpenGL.Net/wiki/OpenGL-ES-using-ANGLE) to create the directory structure, and the provide the libraries specified in [wiki platform page](https://github.com/luca-piccioni/OpenGL.Net/wiki/Platform-Support).

See the [Egl source code](https://github.com/luca-piccioni/OpenGL.Net/blob/master/OpenGL.Net/Egl.cs#L60).

**Comment by luca-piccioni** [comment]
Can you explain why it wasn't clear how the library loads ANGLE libraries? I tried to re-read the wiki, and it seems so clear to myself. :-/ Otherwise you can improve the wiki page, cannot you?

**Comment by equinox2k** [comment]
Ok ive now found out what was happening.. I was following the wiki, and trying all sorts of combinations but when I did try the potentially correct way as per wiki, I was using the nuget repo version of OpenGL .Net v0.3.3 which isn't working, using the compiled dll's from the git repository works.

Steps to reproduce open the Samples\HelloTriangle.ANGLE project, remove references to the OpenGL.Net + OpenGL.Net.Winforms then add the lastest version via nuget.

**Comment by equinox2k** [comment]
Investigated further and turns out the bind Api in Egl.cs below throws exception "unable to load library at libEGL.dll"

LogComment("Querying EGL from {0}", platformLibrary);
BindAPI<Egl>(platformLibrary, OpenGL.GetProcAddress.GetProcAddressOS);

Due to error I thought maybe something wrong with the dll's compiled and made sure I generated the dll's as per... [https://github.com/google/angle/blob/master/doc/BuildingAngleForWindowsStore.md](https://github.com/google/angle/blob/master/doc/BuildingAngleForWindowsStore.md)

But kept getting same error. I have attached the ANGLE dll's ive compiled, can you verify with your own copy of the ANGLE dll's the above line does now throw exception...

[https://www.dropbox.com/s/8jzbw5y3hhfw1sh/ANGLE.zip?dl=0](https://www.dropbox.com/s/8jzbw5y3hhfw1sh/ANGLE.zip?dl=0)

**Comment by equinox2k** [comment]
Further findings and I'm not sure if this is to be expected in private static void BindAPIFunction(string path, FunctionContext functionContext, FieldInfo function, GetAddressDelegate getAddress) for KhronosApi.cs the line importAddress = getAddress(path, importName); throws exception due to eglSetBlobCacheFuncsANDROID not available

**Comment by luca-piccioni** [comment]
Just downloaded you ANGLE (please, use github attachments: dropbox is sooo slow). They substitute my precompiled libraries, HelloTriangle.ANGLE is not running because it complains a missing `msvcp140D_APP.dll`!!`. I suppose because you're following another build target (I'm running on Windows 7; I don't know what WindowsStore is).

Indeed I cannot help you directly. Normally any error on loading library is when the library is dependent on another library: in this case you should load it manually before loading libEGL.dll (this is the case of EGL on Raspberry PI).

A lot of function pointers could be null. Loading is performed using P/Invoke: how an exception is thrown? Can you give me the exact exception information (i.e. the ToString() output, which should include stacktrace and messages)?
