### ISSUE TITLE
how can i apply msaa using glcontrol for winform?

### ISSUE THREAD

**Issue by sukwoo22** [luca-piccioni/OpenGL.Net#35]
i thought it needed to use a frame buffer object to apply msaa like this(https://www.khronos.org/opengl/wiki/Multisampling#Render-to-FBO).
But i found red line in following code,
 Gl.BindTexture(Gl.TEXTURE_2D_MULTISAMPLE, texture);
because Gl.TEXTURE_2D_MULTISAMPLE is not TextureTarget.
Could you fix this problem or give new solution?

**Comment by luca-piccioni** [comment]
If an enumeration is not defined, just cast the constant value to the enum type. They are just ints. 

Sometime the Khronos XML specification misses some enumerants.
