### ISSUE TITLE
Problem with Ubuntu/MonoDevelop 5.1 and target Framework above 'net452'

### ISSUE THREAD

**Issue by wolfgangmauer** [luca-piccioni/OpenGL.Net#43]
If you want/must to develop with MonoDevelop on Ubuntu **(C/C++ Project support)**
it's not possible to target Framework above 'net452'
:-(
Adding OpenGL.Net...
Attempting to resolve dependency 'System.Numerics.Vectors (≥ 4.3.0)'.
Attempting to resolve dependency 'System.Runtime.CompilerServices.Unsafe (≥ 4.3.0)'.
The 'System.Runtime.CompilerServices.Unsafe 4.3.0' package requires NuGet client version '2.12' or above, but the current NuGet version is '2.8.7.0'.

**Comment by luca-piccioni** [comment]
Those dependencies are relative to the binary linked to .Net 4.6.1. The
other binary relative to 3.5 has not dependency. I suppose that nuget is
able to manage dependen ies correctly (it should require dependencies only
if targetting .NET 4.6.1 or above), bit I've never verified.

Lately I've not tested it on Linux boxes, and I've never used nuget on
linux. I suggest to clone the repo and link to the local repository (doing
so you will have also debugging utilities).

Il mar 2 mag 2017, 10:55 wolfgangmauer <notifications@github.com> ha
scritto:

**Comment by luca-piccioni** [comment]
And configure you environment to use nuger 2.12 or newer.
