### ISSUE TITLE
0.5.0 nuget release?

### ISSUE THREAD

**Issue by kf6kjg** [luca-piccioni/OpenGL.Net#44]
I see that a week ago a commit was placed for 0.5.0, but I'm not seeing 0.5.0 in NuGet, only 0.4.2.  Need any help?

**Comment by kf6kjg** [comment]
BTW, I helped the LibreMetaVerse project set up their build system so that tag commits against the master branch done become releases and are automatically uploaded to NuGet.  You can [see the resulting Appveyor config file](https://bitbucket.org/cinderblocks/libremetaverse/src/89b608edc6f58702de97a51ad3757dad3779b480/.appveyor.yml?at=master&fileviewer=file-view-default) if you wish.  I can also help you with setting up Appveyor.

You can do similar with TravisCI as well, just not as cleanly nor as fast.  On a couple of my projects I used both Travis and Appveyor to prove that both Windows (.NET) and Linux (Mono) builds were good.  Both CIs would send the resulting ZIP'd binaries over to GitHub's release page for that version, while Appveyor would also build the NuGet package and send it up to NuGet.org.  Makes releases as easy as:
```BASH
git tag v0.5.0
git push origin --tags
```
And I follow up by going to the fresh release draft on GitHub, filling out the release notes, and publishing.

If you would like something like that here I could guide you through the process if you wish.

**Comment by luca-piccioni** [comment]
Thanks, I'm eager too to release the 0.5.0 version, that will contains additional enumerations, but I'm waiting the merge of this [pull request](https://github.com/KhronosGroup/OpenGL-Registry/pull/51). In case the merge will late too much, I'll push nuget packages all the same (I'm maintaining my own gl.xml).

I didn't know about Appveyor, and automatic nuget management seems a wonderful idea to me; definitively I'll do it. I've already integrated TravisCI, but I develop mainly on Windows and maintaining different solution files for Mono is disturbing my laziness.

A fail on TravisCI was I wasn't able to run my unit tests due missing GL implementation (I tried MESA without success). Do you know anything about this issue on Appveyor? Is it running headless, or I have a chance to get GL rendering on it?

**Comment by luca-piccioni** [comment]
Almost done. Thanks for the template! It was real fun. I think the configuration is OK for the moment. Happily I got a software GL renderer during unit tests! :rofl:

**Comment by kf6kjg** [comment]
yay!  I've been having a tough time with headless/software OpenGL for some time now myself, got a project that wants it, so if you've got some pointers, I'm all ears!

**Comment by luca-piccioni** [comment]
What I'm getting on AppVeyor is

```
Vendor: Microsoft Corporation
Renderer: GDI Generic
Version: 1.1.0
Found 3 GL extensions:
- GL_WIN_swap_hint
- GL_EXT_bgra
- GL_EXT_paletted_texture
```

On TravisCI I was able to start tests on GLX, by installing the packages via travis.yml:

```
addons:
  apt:
     packages:
        - xserver-xorg-video-dummy
        - xpra
        - mesa-utils
```

However, I got only crashes on MESA native stack, missing pointers; I wasn't able to run fully a test (yet not even now on my local machine :sob: )
