### ISSUE TITLE
Game Loop

### ISSUE THREAD

**Issue by LordSkittles** [luca-piccioni/OpenGL.Net#46]
Hi, I was wondering is there a way to continuously call the render event every frame so that you could essentially make a game editor in windows forms.

**Comment by luca-piccioni** [comment]
This commit should resolve your issue: https://github.com/luca-piccioni/OpenGL.Net/commit/4089196b171f8d63990e91b9271f702814e3e3f7

Essentially set Animation to true.

**Comment by LordSkittles** [comment]
Thanks! When will this be added to the NuGet package?

**Comment by luca-piccioni** [comment]
Yeah, I'm playing on it. When everything is automated with AppVeyor, I'll push the master branch on nuget.

**Comment by LordSkittles** [comment]
Thanks. You're a legend Luca!

**Comment by LordSkittles** [comment]
Hey, so I ended up doing it the build way, and now the program launches, but crashes instantly, but still has items going on in the background. Any ideas?

**Comment by luca-piccioni** [comment]
Debug? Exception message and stack trace? 
By the way, you can upgrade to 0.5.1-beta, upload ed yesterday.
