### ISSUE TITLE
Dll error binding

### ISSUE THREAD

**Issue by DjArt** [luca-piccioni/OpenGL.Net#47]
When I try run my app at WIndows 8.1 RT with opengl-to-directx wrapper, located at System32 or folder with my app, your lib can't find opengl32.dll, but other native(c++) apps can find and use this wrapper.
P.S. Yeah, it's very specific case, Windows RT doesn't support OpenGL and officially don't support run other applications. I can provide some information, if you needed.

**Comment by luca-piccioni** [comment]
What is the specific exception information? What is your platform library? WGL or EGL?

Anyway you can map [libraries](https://github.com/luca-piccioni/OpenGL.Net/wiki/GL-%5C-Platform-Support) using your app.config, even just fir experimenting.

**Comment by DjArt** [comment]
![4](https://cloud.githubusercontent.com/assets/1651555/26169661/2450d3d6-3b71-11e7-9b39-7ca7c2a2ad01.png)
I get this error. And I'm use WGL, I think so. What I need to write in app.config for path setting?

**Comment by luca-piccioni** [comment]
The app.config can be created within Visual Studio (search in templates), and you can follow the [mono documentation](http://www.mono-project.com/docs/advanced/pinvoke/dllmap/) about it.

OpenGL.Net simply uses the "opengl32.dll" string for requesting the library handle; indeed there's something in your system configuration that is confusing the OS loader. The first thing that comes in my mind is the process bitness: are you running on x86 or x64? What is the bitness of your process? The nuget package binary have Any CPU as target, letting the application force the x86 or the x64 JIT. Another thing could be the Windows side-by-side configuration.

At first, have you tried to put your opengl32.dll on the same working directory of your application?

**Comment by DjArt** [comment]
I'm running on ARM32. Yes, I'm tried put opengl32.dll in app folder, but no changes.

**Comment by luca-piccioni** [comment]
Are there any opengl32.dll dependencies unresolved? Use dumpbin or the dependency walker to get this information.

**Comment by DjArt** [comment]
All dependencies resolved. But configuring via app.config helps! Thanks you!
