### ISSUE TITLE
Problem with GTK#

### ISSUE THREAD

**Issue by sourceskyboxer** [luca-piccioni/OpenGL.Net#49]
I have tried but it doesn't show Gl-Viewport on Gtk.Window -
It always hide me.

Example code for Window or Container If I don't know that.
```
using Gtk;
using OpenGL;

namespace GtkGame{
    class GtkGameWindow : Window
    {
        public bool GLinit;

        public GtkGameWindow() : base(WindowType.Toplevel)
        {
            GLinit = false;
            WidgetEvent += new WidgetEventHandler(GtkInitalizeHanlder);
        }

        private void GtkInitalizeHanlder(object sender, WidgetEventArgs we)
        {
            int width = 0, height = 0;
            GetSizeRequest(out width, out height);
            float aspectRatio = width / height;
            Gl.Viewport(0, 0, width, height);
            Gl.ClearColor(1.0f, 1.0f, 1.0f, 1.0f);
            Gl.Clear(ClearBufferMask.ColorBufferBit);
            Gl.MatrixMode(MatrixMode.Modelview);
            Gl.LoadIdentity();
            Gl.ShadeModel(ShadingModel.Smooth);
            //Matrix4 projection = Matrix4.CreatePerspectiveFieldOfView((float)Math.PI / 4, aspectRatio, 1.0f, 64.0f);
            Gl.MatrixMode(MatrixMode.Projection);

            Gl.ClearDepth(1);
            Gl.Disable(EnableCap.DepthTest);
            Gl.Enable(EnableCap.Texture2d);
            Gl.Enable(EnableCap.Blend);
            Gl.DepthFunc(DepthFunction.Always);
            Gl.Hint(HintTarget.PerspectiveCorrectionHint, HintMode.Nicest);
            //add idle event handler to process rendering whenever and as long as time is availble.
            GLinit = true;
        }
    }
}
```
But I found example but it is old of OpenTK [StackOverFlow](https://stackoverflow.com/questions/9778875/how-to-render-using-opentk-glwidget-in-monodevelop)

I try replace - But OpenGL Matrix4x4 hasn't static method CreatePerspectiveFieldOfView(). How do I fix for replacement of your OpenGL.net

**Comment by luca-piccioni** [comment]
Use `PerspectiveProjectionMatrix`, or `OrthoProjectionMatrix` if you want an orthographic projection. I'm evaluating the introduction of methods like `CreatePerspectiveFieldOfView`, it seems more intuitive for many users.

You should elaborate more about your GTK# solution. I've never tried that toolkit, even if I always wished to implement it. For example: who creates the device context? I fear that you really should call `Gl.BindAPI()` before using `Gl` methods.

**Comment by sourceskyboxer** [comment]
Thanks for resolving.. I will fix it

**Comment by luca-piccioni** [comment]
Well, the commit reference above is my first shot on GTK3. It actually does not work, I suspect because there is some misunderstanding about the double buffer (essentially the widget does not swap the buffers. The commit introduce a new sample, and try to create a DrawingArea that creates the GL context, and draw on itself. The GL context and it concurrency is managed correctly, but the buffers are not swapped.

OpenGL.Net is not aware about the windowing system. You need a display handle and a window handle to create a GL context; those handles must be the ones that wglCreateContextAttribs expect to get, and obviously this is platform dependent.

The GTK sample is essentially based on [this code](https://github.com/Nihlus/GLWidgetTest/blob/master/GLWidget/GLWidgetGTK3/GLWidget.cs), linked to this [Question on mono](http://mono.1490590.n4.nabble.com/GTK-3-OpenGL-widget-under-Windows-td4668627.html). I had changed the `gdk_win32_drawable_get_handle,` because it returns always `IntPtr.Zero` whatever handle I passed to it. Currently I can create a GL context, but I'm not sure if the handles are actually linked to the widget or the window of anything else.

**Comment by luca-piccioni** [comment]
The solution on windows is to pass to `DeviceContext.Create` the handle returned by [CreateWindowW](https://msdn.microsoft.com/en-us/library/windows/desktop/ms632679(v=vs.85).aspx). Indeed the question is: how to get that handle from GTK?

**Comment by sourceskyboxer** [comment]
Thanks I will try later..

**Comment by sourceskyboxer** [comment]
So now I say that bad support :( So sad because I already tried and it gots error :( 24/25 not working now.

I think I recommend with OpenGL.net because it has default gtk3 it hasn't problem with OpenTKL. Yay

Now I am working. Thanks!

**Comment by sourceskyboxer** [comment]
Sorry for that forget to say... I have problem if I call eventhandler why does GLWidgetEventArgs doesn't exist - if i use

> glWidget.ContextCreated += new EventHandler.<GlWidgetEventArgs>(MyCreatedListener);
> 
> private void MyCreatedListener(object sender, GlWidgetEventArgs e)
> {
> ...
> }

Shows error syntax 👎 

I try to use delegate function

like this

> glWidget.ContentCreated += delegate {
> ...
> };

Why does example gtk app not show triangle  :(

I really miss that. :( I wish I understand because I want create my own application for Half-Life :(

I tried example but after compiled shows only white screen????????????

> using System;
> 
> using Gtk;
> using OpenGL.GTK3;
> using OpenGL;
> 
> namespace HelloTriangle.GTK
> {
> 	class ExampleWindow : Window
> 	{
>         private GlWidget glWidget;
>         private static float _Angle;
>         private static readonly float[] _ArrayPosition = new float[] {
>             0.0f, 0.0f,
>             0.5f, 1.0f,
>             1.0f, 0.0f
>         };
>         private static readonly float[] _ArrayColor = new float[] {
>             1.0f, 0.0f, 0.0f,
>             0.0f, 1.0f, 0.0f,
>             0.0f, 0.0f, 1.0f
>         };
> 
>         private MemoryLock vertexArrayLock = new MemoryLock(_ArrayPosition);
>         private MemoryLock vertexColorLock = new MemoryLock(_ArrayColor);
> 
>         public ExampleWindow() : base("Hello Triangle (GTK# 3)")
> 		{
> 			SetDefaultSize(800, 600);
> 			SetPosition(WindowPosition.Center);
> 
> 			glWidget = new GlWidget();
> 
> 			Add(glWidget);
> 
>             glWidget.SetSizeRequest(100, 100);
> 
>             glWidget.ContextCreated += delegate
>             {
>                 Gl.MatrixMode(MatrixMode.Projection);
>                 Gl.LoadIdentity();
>                 Gl.Ortho(0.0, 1.0, 0.0, 1.0, 0.0, 1.0);
> 
>                 if (glWidget.MultisampleBits > 0)
>                 {
>                     Gl.Enable(EnableCap.Multisample);
>                 }
>             };
> 
>             glWidget.Render += delegate
>             {
>                 Gl.Viewport(0, 0, glWidget.WidthRequest, glWidget.HeightRequest);
>                 Gl.Clear(ClearBufferMask.ColorBufferBit);
> 
>                 Gl.MatrixMode(MatrixMode.Modelview);
>                 Gl.LoadIdentity();
>                 Gl.Rotate(_Angle, 0.0f, 0.0f, 1.0f);
> 
>                 Gl.VertexPointer(2, VertexPointerType.Float, 0, vertexArrayLock.Address);
>                 Gl.EnableClientState(EnableCap.VertexArray);
> 
>                 Gl.ColorPointer(3, ColorPointerType.Float, 0, vertexColorLock.Address);
>                 Gl.EnableClientState(EnableCap.ColorArray);
> 
>                 Gl.DrawArrays(PrimitiveType.Triangles, 0, 3);
>             };
> 
>             glWidget.ContextUpdate += delegate
>             {
>                 _Angle = (_Angle + 0.1f) % 45.0f;
>             };
> 
>             DeleteEvent += delegate { Application.Quit(); };
> 			ShowAll();
> 		}
> 	}
> 
> 	static class Program
> 	{
> 		/// <summary>
> 		/// Punto di ingresso principale dell'applicazione.
> 		/// </summary>
> 		[STAThread]
> 		static void Main()
> 		{
> 			Application.Init();
> 			new ExampleWindow();
> 			Application.Run();
> 		}
> 	}
> }

And it doesn't work? Or I should use Gl.Shader feature?

Please give me example..... Thanks!
