### ISSUE TITLE
NuGet package

### ISSUE THREAD

**Issue by varon** [luca-piccioni/OpenGL.Net#5]
Congratulations on reaching your first binary release. It's nice to see that the project has reached that level of maturity.

Could we look at getting the library made available as a NuGet package? It shouldn't be super hard, and would encourage people to start using it.

**Comment by luca-piccioni** [comment]
Just working on nuget, this morning. However, only OpenGL.Net library will
be released... Other binaries are still not usable for a typical user.

Il Sab 12 Mar 2016 08:12 varon <notifications@github.com> ha scritto:
