### ISSUE TITLE
WindowsFormsHost issue

### ISSUE THREAD

**Issue by amarkatti** [luca-piccioni/OpenGL.Net#52]
i am trying to create hellotriangle wpf application and I am getting the error " WindowsFormsHost is not supported on wpf". I have installed opengl.net nugget package into my solution. 
Can someone please help me resolve the issue ?

**Comment by luca-piccioni** [comment]
The error description is too vague to effectively solve your problem. Give the exception stack trace, and a describe the context where the exception is thrown (i.e. at design-time or run-time?

I've tried to google on this issue, and it seems that very few people cannot host a WinForms control in a WPF application.
