### ISSUE TITLE
Missing framebuffer target

### ISSUE THREAD

**Issue by JasSra** [luca-piccioni/OpenGL.Net#53]
Hi ,
 I am trying to figure that in Opengl 4 + , there is an target"GL_DEPTH_STENCIL_ATTACHMENT" specified by the Khronos for Framebuffer. However, its not available in the enums specified for that function. Am i missing something.

ref
https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glFramebufferRenderbuffer.xhtml

Thanks

**Comment by luca-piccioni** [comment]
I'll fix it. I the meanwhile, you can cast the raw costant Gl.DEPTH_STENCIL_ATTACHMENT.
