### ISSUE TITLE
How does the library work with .NET Core and Windows?

### ISSUE THREAD

**Issue by jorisvdstraten** [luca-piccioni/OpenGL.Net#59]
Not sure about this... I tried to run the .NET Core samples on my Windows machine, but they didn't work and seemed to try and load the VideoCore libraries?

**Comment by luca-piccioni** [comment]
Can you define "they didn't work"?

The OpenGL.Net library is compiled against the .NET Core framework. The EGL, GLX and EGL libraries are used accordingly to the running platform.

VideoCore library query is currently implicit, and it is executed at initialization time. I can decouple OpenGL.Net from VideoCore completly, but at the moment it's easier to have it integrated.
