### ISSUE TITLE
Versioning scheme + Release notes

### ISSUE THREAD

**Issue by varon** [luca-piccioni/OpenGL.Net#6]
It would probably be a good idea to adopt a reasonable versioning strategy. While not perfect, [SEMVER ](http://semver.org/)is a pretty good starting point. Feel free to use any scheme you'd like, as long as you can point users to a documentation on what the versions are supposed to mean.

Additionally, and directly related to the versioning is a RELEASE_NOTES.md.file - it would make tracking changes much easier.

To tie all of this (and Issue #5) together, I'd suggest looking at [FAKE](http://fsharp.github.io/FAKE/) to manage the build process.

**Comment by luca-piccioni** [comment]
Initially I was toward to starting from 1.0.0, but now I'm thinking to
align OpenGL.Net version to the actual OpenGL specification implemented.

Il Sab 12 Mar 2016 08:19 varon <notifications@github.com> ha scritto:

**Comment by varon** [comment]
That sounds like a pretty good idea, although I'd suggest a minor version to allow for updates.

More to the point: does OpenGL.Net not support different versions of OpenGL? It would probably greatly increase it's usage if several versions were made available.

**Comment by luca-piccioni** [comment]
At the end I choose to start versioning from 0.1... Not very attractive, but better than asserting a 4.5. 0 version. 

OpenGL.Net loads dynamically the OpenGL functions available on current system. Indeed it can support from OpenGL 1.0 from the last one compiled in library (and consider that support all extensions). Sadly it supports only desktop OpenGL.

Lets say that it is a GLEW for C#.

**Comment by varon** [comment]
Sounds good for now. It's also SEMVER compatible, which is a bonus.

**Comment by varon** [comment]
What's the plan for the release notes?

**Comment by luca-piccioni** [comment]
The file RELEASE_NOTES.md is already pushed. I think it will contains notes about API changes, such as introduced extensions, but without tracking changes on single API commands, otherwise it will end to a log of the Khronos changes.
