### ISSUE TITLE
OpenGL.Net crashes on Linux

### ISSUE THREAD

**Issue by Nihlus** [luca-piccioni/OpenGL.Net#7]
On systems where the "uname" binary is not present in /usr/bin/, any call to the Gl object causes a crash due to the file not being found. Creating a symbolic link to the real binary (present in /bin/ on some systems) functions as a workaround.

**Comment by luca-piccioni** [comment]
What's the actual path of uname on your system? What's the type of the
exception thrown?

If the uname is located in /bin it should be found, unless an unexpected
exception is not caught.

Il Gio 7 Apr 2016 22:04 Jarl Gullberg <notifications@github.com> ha scritto:

**Comment by Nihlus** [comment]
The actual path of uname is /bin/uname - I think it may crash on the first attempt to access the invalid /usr/bin/uname path before it has a chance to try the others.

Here's the full exception: https://gist.github.com/Nihlus/43fb2b47ccbe04056185649360711f0a

**Comment by luca-piccioni** [comment]
Quite strange: the exception should be caught and the next iteration shall
test /bin/uname path, as you can see in DetectUnixKernel method in
https://github.com/luca-piccioni/OpenGL.Net/blob/master/OpenGL.Net/GetProcAddress.cs

P. S. : since I've not run anything on Linux yet, how is going?

Il Ven 8 Apr 2016 11:42 Jarl Gullberg <notifications@github.com> ha scritto:

**Comment by Nihlus** [comment]
The version I'm using is from Nuget (version 0.2.0.0) - perhaps that one is outdated?

I haven't been able to test much yet :) I'm fairly new to the whole OpenGL thing, and is stumbling around not really knowing what to do. Currently, I'm trying to render a model in a Gtk3 UI, and I'm not getting anywhere. If you have any tips, I'd be happy to hear them :D

**Comment by luca-piccioni** [comment]
That code exists from the beginning, and it is derived from Tao Framework.
Maybe I'll write some non-graphics unit test to run on Travis servers to
test that code.

You should check unit tests and OpenGL.Hal sources to have an idea how to
manage OpenGL.

Il Ven 8 Apr 2016 12:45 Jarl Gullberg <notifications@github.com> ha scritto:

**Comment by luca-piccioni** [comment]
Did you managed to draw on GTK3 widget?

**Comment by Nihlus** [comment]
I've since moved on to OpenTK, but using that I have indeed managed to render a viewport inside a GTK3 window.
