### ISSUE TITLE
Typo, PerspectiveProjectionMatrix.SetFustrum() missing an 'r'

### ISSUE THREAD

**Issue by madpew** [luca-piccioni/OpenGL.Net#75]
Feels bad to open this as an "issue", it's an easy fix, but maybe it encourages someone to check the whole codebase for typos.

https://github.com/luca-piccioni/OpenGL.Net/blob/c76a6203851a2df599230925b464e420b7445697/OpenGL.Net/ProjectionMatrix.cs#L450

**Comment by luca-piccioni** [comment]
Thank you. Issues are always welcome; no reason to feel bad about it.
