### ISSUE TITLE
DrawString capabilties

### ISSUE THREAD

**Issue by wzydhek** [luca-piccioni/OpenGL.Net#76]
Are there any DrawString capabilities? Or some other way to draw text?

**Comment by luca-piccioni** [comment]
OpenGL.Net is a plain wrapper for OpenGL commands.
If you want to draw characters, try [vector](https://github.com/luca-piccioni/OpenGL.Net/blob/master/OpenGL.Net.Objects/FontVertex.cs) or [texture](https://github.com/luca-piccioni/OpenGL.Net/blob/master/OpenGL.Net.Objects/FontTextureArray2d.cs) font implementation in OpenGL.Net.Objects. Anyway too invasive for a single functionality.

Or implement it yourself.
