### ISSUE TITLE
OpenGL.CoreUI does not exist .NET Core 2.0

### ISSUE THREAD

**Issue by HUg0005** [luca-piccioni/OpenGL.Net#78]
When trying `using OpenGL.CoreUI` on .NET Core 2.0 after installing the [nuget package](https://www.nuget.org/packages/OpenGL.Net/) I get the error saying something along the lines of `namespace CoreUI does not exist`. Help would be much appreciated (I'm using Ubuntu 17.10).

**Comment by luca-piccioni** [comment]
The CoreUI namespace is not included in nuget package (it will be in a separated package, anyway).

Moreover, the CoreUI currently support only Windows (altought it should be straightforward to support Linux too).

**Comment by HUg0005** [comment]
How do you create a window then without the NativeWindow class? (I'm new to OpenGL programming)

**Comment by luca-piccioni** [comment]
The `NativeWindow` can be created with the [factory pattern](https://github.com/luca-piccioni/OpenGL.Net/blob/master/OpenGL.Net.CoreUI/NativeWindow.cs#L806), just extend NativeWindow with a class `NativeWindowX11` (or `NativeWindowGLX`), which implements windowing using XLib/X11 methods.

You can start from [scratch](https://www.khronos.org/registry/OpenGL-Refpages/gl2.1/xhtml/glXIntro.xml) using an authoritative sample, just translating calls using P/Invoke (Glx has the necessary definitions, they could made public). A faster method could be copy and replicate the [internal implementation](https://github.com/luca-piccioni/OpenGL.Net/blob/master/OpenGL.Net/DeviceContextGLX.cs#L144) of the native window.

At the moment in CoreUI there is only the strictly necessary for running .NET Core 1/2 samples on Windows, and I don't require anymore; your can PR the Linux implementation, if you wish; however, be warned that recently I've noticed instabilities when using my GLX implementation.
