### ISSUE TITLE
Build fails when following instruction exactly.

### ISSUE THREAD

**Issue by matthew798** [luca-piccioni/OpenGL.Net#79]
I cloned the source, opened x64 native tools vs2017, cd'd to the source directory and ran the command that is in the readme. I get:

> 
> error MSB4126: The specified so
> lution configuration "Release|x64" is invalid. Please specify a valid solution configuration using the Configuration an
> d Platform properties (e.g. MSBuild.exe Solution.sln /p:Configuration=Debug /p:Platform="Any CPU") or leave those prope
> rties blank to use the default solution configuration. [C:\Users\user\Source\Repos\OpenGL.Net\OpenGL.N
> et_VC14.sln]

Same thing for VC15.sln

I can't even build the solution. I'm using vs2017 pro v15.4.3

Thanks.

**Comment by luca-piccioni** [comment]
Once added x64 configurations, it compiles fine. It was an opportunity yo review the platform configurations (very tedius to setup and maintain).

x86 configurations does not pass some unit test on AppVeyor. I'll check later.

**Comment by luca-piccioni** [comment]
Good, now run even on x86 without issues.

**Comment by matthew798** [comment]
Thanks!
