### ISSUE TITLE
GLM OpenGL Mathemathics library

### ISSUE THREAD

**Issue by ktheijs** [luca-piccioni/OpenGL.Net#80]
I am loving this project so far! Are there any plans to include the GLM? Or do you propose a different approach to do these kinds operations?

**Comment by luca-piccioni** [comment]
Really OpenGL.Net API is not dependent by any specific math library. Indeed you are free to choose whatever math library you like.

In the repository, there is OpenGL.Net.Math project, defining OpenGL-like structures for vertices and matrices. In the next nuget packages OpenGL.Net and OpenGL.Net.Math will be decoupled, indeed it will require an additional nuget installation.
