### ISSUE TITLE
nativeWindow.MouseMove Y coordinates are inverted

### ISSUE THREAD

**Issue by matyasforian** [luca-piccioni/OpenGL.Net#90]
The zero Y coordinate is at the bottom of the window, its max value at the top. Is this intentional?
OpenGL.NET 0.7.1 on Windows 10.

**Comment by luca-piccioni** [comment]
Yep, it is [intentional](https://github.com/luca-piccioni/OpenGL.Net/blob/master/OpenGL.Net.CoreUI/NativeWindowWinNT.cs#L260).

I did this in the past 10 years for every new project. The idea is to set the window origin to the bottom-left, as glViewport does.

**Comment by matyasforian** [comment]
OK, thanks!
